### ISSUE TITLE
Reminding users with negative balance

### ISSUE THREAD

**Issue by problame** [hadiko-i6/i6getraenkeabrechnungssystem3000#3]
Users with negative account balance should be reminded of that each time they interact with the system
- [ ] Highlight negative account balance in red (in the overview table)
- [ ] Nag in confirmation dialog. Ideas
  - Timeout until the buttons appear, with indicative message at their position during the timeout
  - Indicative, highlighted message below the 'Are you X' question

**Comment by DrLuke** [comment]
Nagging has been implemented: e4b0309c8c98de8e8aefd5b8d66c3675cc605888
An animated label is displayed during the confirmation dialog and is located next to the confirmation buttons.
I strongly object against obstructing the confirmation process by adding a timeout before the confirmation button can be pressed, as I believe that it will lead to people not confirming their order.
